### ISSUE TITLE
Logged in players showing as not logged in

### ISSUE THREAD

**Issue by xnite** [ticklemynausea/idlerpg#2]
I didn't notice this until setting up the website for irpg at http://idle.AfraidIRC.net, but when players are logged in they are not appearing to always be logged in on the site. I was able to pin point the issue down to the database, where in the logged_in field there is a 0 instead of a 1 for logged in players. After seeing that nobody is appearing in the database as being logged in, I attempted to log into the bot which stated that I am already logged in.
Clearly something is wrong here, I'm wondering if the bot is just not updating the database or if the logged in status is being reset on file and kept in memory or what.

**Comment by urbels** [comment]
For me everything is ok - http://irpg.o-o.lv/players.php

**Comment by xnite** [comment]
weird, I keep seeing in the database that users who are  online are off, sometimes they will blip online for a bit, but idk. Could I see your irpg configuration and see if maybe I did something wrong? (exclude any private info such as nickserv passwords ofc) :)

**Comment by urbels** [comment]
It`s default idlerpg config.
